### ISSUE TITLE
Hush3 unable to make shielded transactions

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [webworker01/knomp#23]
I built an instance of K-nomp, and have everything running perfectly when using transparent R addresses on HUSH3.

I've been informed Hush will be switching to shielded address by default and wanted to be ahead of the game. As such I set "privatechain:true" and "burnfees:true" in the coin conf as per documentation.

Now I am able to validate Z addresses correctly however, when blocks are found and confirmed and it's time for payouts I receive an error stating:
-could not find coinbase utxos to spend
-coinbase utxos can only be sent to a single Z address.

I now have 25+ blocks stuck and unable to properly payout. Is there a simple setting fix for this? Or do I need to modify the backend to make this work?

**Comment by webworker01** [comment]
If it works like Pirate it should work.

Make sure you have R and Z address set and imported to your wallet. Check your logs for op-ids and make sure those are happening.

**Comment by l8nit3tr0ubl3** [comment]
Actually I believe I've managed to fix it by simply switching z_sendmany to z_shieldcoinbase (and the required "params"). Now the script is at least able to properly shield the transparent funds... I will update afterwards if payouts run aswell.

If so I'll submit a PR.

**Comment by webworker01** [comment]
I'll look at it. I understood them both to basically do the same thing.

Try this config, the `disablecb` param might be the difference

```{
"name": "HUSH3Z",
"symbol": "HUSH3Z",
"algorithm": "equihash",
"txfee": 0.0001,
"peerMagic": "6ed394d3",
"sapling": true,
"disablecb": true,
"privateChain": true
}
```
