### ISSUE TITLE
3 days ago repository worked fine on fresh ubuntu

### ISSUE THREAD

**Issue by 49handyman** [webworker01/knomp#26]
today im setting up another backup server and followed my notes to the letter, which is what you basically have in the Docker build file to ensure it worked again.

now it fails on bignum.
-----------------------------------------------------------------------------------------------------------------------------------
 npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> bignum@0.13.0 install /home/ubuntu/knomp/node_modules/bignum
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.14.2 runtime=node arch=x64 platform=linux)
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/ubuntu/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/ubuntu/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/ubuntu/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 5.4.0-1037-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v10.14.2/bin/node" "/home/ubuntu/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/knomp/node_modules/bignum
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bignum@0.13.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-02-26T04_06_17_008Z-debug.log
ubuntu@ip-172-31-49-118:~/knomp$

**Comment by webworker01** [comment]
read install instructions or use docker file

**Comment by 49handyman** [comment]
my bad
