### ISSUE TITLE
PIRATE pool ACCEPTED share?

### ISSUE THREAD

**Issue by goodthebest** [webworker01/knomp#30]
Hey guys @webworker01 @TheComputerGenie @NutellaLicka 
I've a confusion for this PIRATE pool, in the pool log I do not see SHARE ACCEPTED message, however on the website I do see shares are counted and accepted. How can ACCEPTED SHARE message be logged and enabled in pool log?

I have appended three files for PIRATE pool configuration using knomp, please have a look and suggest if any correction needs to be made? 

## /pool_configs/PIRATE.json

   {
  "enabled": true,
  "coin": "PIRATE.json",
  "address": "RJsTaEu7aLC-REDACTED",
  "zAddress": "zs1u4knjhdmrxnuy3vgaxssee-REDACTED",
  "tAddress": "RXKBEGxg1nxMoZkjGaWafbB-REDACTED",
  "walletInterval": 1,
  "tlsOptions": { "enabled": false },
    "paymentProcessing": {
        "enabled": true,
        "minConf": 10,
        "paymentMode": "prop",
        "_comment_paymentMode": "prop, pplnt",
        "paymentInterval": 1800,
        "minimumPayment": 0.05,
        "maxBlocksPerPayment": 3,
        "daemon": {
            "host": "127.0.0.1",
            "port": 45453,
            "user": "-REDACTED",
            "password": "-REDACTED"
        }
    },

  "trackShares": { "enable": true },
  "ports": {
      "3333": {
          "tls":false,
          "diff": 0.001,
          "varDiff": {
              "minDiff": 0.001,
              "maxDiff": 1000,
              "targetTime": 15,
              "retargetTime": 60,
              "variancePercent": 30

          }
      }
  },

  "daemons": [{
      "host": "127.0.0.1",
      "port": 45453,
      "user": "-REDACTED",
      "password": "-REDACTED"
  }],
  "p2p": {
      "enabled": false,
      "host": "127.0.0.1",
      "port": 52042,
      "disableTransactions": true
  },
  "mposMode": { "enabled": false }
}

## config.json

   {
    "logLevel": "debug",
    "_logLevelOptions": "debug/info/warning/error",
    "logColors": true,

    "heapdumpSeconds": false,

    "cliPort": 17117,

    "clustering": {
        "enabled": true,
        "forks": 1
    },

    "defaultPoolConfigs": {
        "blockRefreshInterval": 0,
        "jobRebroadcastTimeout": 55,
        "connectionTimeout": 600,
        "emitInvalidBlockHashes": false,
        "validateWorkerUsername": false,
        "tcpProxyProtocol": false,
        "banning": {
            "enabled": false,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 500,
            "purgeInterval": 300
        },
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "password": ""
        }
    },

    "website": {
        "enabled": true,
        "host": "0.0.0.0",
        "port": 8080,
        "stratumHost": "192.168.1.242",
        "template": "default",
        "stats": {
            "updateInterval": 30,
            "historicalRetention": 14400,
            "hashrateWindow": 300
        },
        "adminCenter": {
            "enabled": false,
            "password": "password"
        },
        "tlsOptions" : {
            "enabled": false,
            "cert": "",
            "key": ""
        }
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "switching": {
        "switch1": {
            "enabled": false,
            "algorithm": "sha256",
            "ports": {
                "3333": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch2": {
            "enabled": false,
            "algorithm": "scrypt",
            "ports": {
                "4444": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch3": {
            "enabled": false,
            "algorithm": "x11",
            "ports": {
                "5555": {
                    "diff": 0.001,
                    "varDiff": {
                        "minDiff": 0.001,
                        "maxDiff": 1,
                        "targetTime": 15,
                        "retargetTime": 60,
                        "variancePercent": 30
                    }
                }
            }
        }
    },

    "profitSwitch": {
        "enabled": false,
        "updateInterval": 600,
        "depth": 0.90,
        "usePoloniex": true,
        "useCryptsy": true,
        "useMintpal": true,
        "useBittrex": true
    }
}

## /coins/PIRATE.json

   {
  "name": "pirate",
  "symbol": "ARRR",
  "algorithm": "equihash",
  "txfee": 0.00005,
  "sapling": true
}

**Comment by TheComputerGenie** [comment]
![image](https://user-images.githubusercontent.com/21057518/171954528-8f5113ae-ba2d-49e1-8c68-435e94a28edf.png)
You don't want to see them

**Comment by goodthebest** [comment]
@TheComputerGenie yes I got your point, but is there a way I can enable ACCEPTED shares?

**Comment by TheComputerGenie** [comment]
You'd have to add a console log in jobManager.js
No one does this because shares come in at a rapid rate and you don't want your screen flooded with share data to the point where you cannot see the meaningful stuff

**Comment by webworker01** [comment]
You can just see shares on the web interface are counted on your worker page
