### ISSUE TITLE
Blocknotify or P2P  What to choose?

### ISSUE THREAD

**Issue by Russel20s** [webworker01/knomp#31]
Hello, please explain what is better to choose and what is the difference.
Or include both?

The manual says that P2P has an advantage. Can you explain that it's better to leave all of these?

"/* This allows the pool to connect to the daemon as a node peer to receive block updates.
       It may be the most efficient way to get block updates (faster than polling, less
       intensive than blocknotify script). It requires the additional field "peerMagic" in
       the coin config. */
    "p2p": {
        "enabled": false,
 
        /* Host for daemon */
        "host": "127.0.0.1",
 
        /* Port configured for daemon (this is the actual peer port not RPC port) */
        "port": 19333,
 
        /* If your coin daemon is new enough (i.e. not a shitcoin) then it will support a p2p
           feature that prevents the daemon from spamming our peer node with unnecessary
           transaction data. Assume its supported but if you have problems try disabling it. */
        "disableTransactions": true"

**Comment by webworker01** [comment]
Do not use issues for Q&A
