### ISSUE TITLE
Payout problem with PIRATE

### ISSUE THREAD

**Issue by goodthebest** [webworker01/knomp#32]
@webworker01 @TheComputerGenie 
**Describe the bug**
Payout problem, found two blocks hundreds of confirmations already done but knomp website still showing block pending. I've attached screenshot as well as PIRATE.json files, please have a look.

**Screenshot**
two blocks found so far but it says insufficient balance, each block is 16 but it's asking for 32.003 balance?
![image](https://user-images.githubusercontent.com/1715740/172058772-8b13442c-b797-4f47-a00b-2faffa120669.png)

**coins/PIRATE.JSON**
{
  "name": "pirate",
  "symbol": "ARRR",
  "algorithm": "equihash",
  "peerMagic": "58e0b617",
  "disablecb": false,
  "requireShielding": true,
  "privateChain": true,
  "txfee": 0.0001,
  "sapling": true
}

**pool_confirgs/PIRATE.JSON**
{
  "enabled": true,
  "coin": "PIRATE.json",
  "address": "RJsTaEu7aL-REDACTED",
  "zAddress": "zs1u4knjhdmrxnuy3vga-REDACTED",
  "tAddress": "RXKBEGxg1nxMoZkjGaWafbBRSMYPccibxd",
  "walletInterval": 600,
  "rewardRecipients": {"RXKBEGxg1nx-REDACTED": 1.0},
  "tlsOptions": { "enabled": false },
    "paymentProcessing": {
        "payOnStart": true,
        "enabled": true,
        "minConf": 3,
        "paymentMode": "prop",
        "paymentInterval": 300,
        "minimumPayment": 1,

**Comment by webworker01** [comment]
How about transaction fees?

**Comment by goodthebest** [comment]
> How about transaction fees?

Do we need to top up pool wallet to cover transaction fees?

**Comment by webworker01** [comment]
Please only submit bug reports here
