### ISSUE TITLE
NOMP Project Scattered Work

### ISSUE THREAD

**Issue by nettts** [webworker01/knomp#8]
repo manager,

The scattered pool software development is a pain for everyone. Please consider contributing this fork back to https://github.com/s-nomp/s-nomp where we're trying to support all coins with z-nomp.

Requiring a pool operator to search all over github for the correct software is inefficient and makes the whole thing "less valuable". Motivation isn't there. The time wasted on this whole searching and supporting different projects is extremely time consuming. Let's think of this more as a business model and support our users by simplifying  their management.

Just take this into consideration. We'd love to merge the work done here and add you to the contributor list. Thank you.

**Comment by webworker01** [comment]
https://github.com/s-nomp/s-nomp/issues/74
